### ISSUE TITLE
Rework registration tool to use antspy

### ISSUE THREAD

**Issue by ataha24** [afids/autoafids_prep#4]
Enables an packaging and since niftyreg is not as manintained anymore. Will need to possibly rework some scripts to take in the ANTS transform output rather than niftyreg

**Comment by Dhananjhay** [comment]
Transition from NiftyReg to ANTsPy has been done, but the registration is not performed correctly at the moment. We suspect it's a problem either with the outputted 4x4 transformation matrix or the registration script. This needs further investigation.
